name: Check code validity
on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Check project compiles
        run: mvn --batch-mode verify
