name: Check code validity
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Check project compiles
        run: ./mvnw --batch-mode clean install
      - name: Check core example
        run: cd examples/example-core && ./mvnw --batch-mode clean test
      - name: Check full example
        run: cd examples/example-full && ./mvnw --batch-mode clean test
