name: Publish to Maven Central Repository
on:
  release:
    types: [ created ]
  pull_request:
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{secrets.GPG_PRIVATE_KEY}}
          passphrase: ${{secrets.GPG_PASSPHRASE}}
      - name: List keys
        run: gpg -K
      - name: Set up Java for publishing to Maven Central Repository
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: central
          server-username: OSSRH_USERNAME
          server-password: OSSRH_TOKEN
          gpg-private-key: GPG_PRIVATE_KEY
          gpg-passphrase: GPG_PASSPHRASE
      - name: Publish to the Maven Central Repository
        run: ./mvnw --batch-mode -Dusername=${{secrets.OSSRH_USERNAME}} -Dpassword=${{secrets.OSSRH_TOKEN}} -Dpassphrase=${{secrets.GPG_PASSPHRASE}} -s settings.xml -Prelease-sign-artifacts clean deploy
        env:
          OSSRH_USERNAME: ${{secrets.OSSRH_USERNAME}}
          OSSRH_TOKEN: ${{secrets.OSSRH_TOKEN}}
          GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}
          GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}
#      - name: Set up Java for publishing to GitHub Packages
#        uses: actions/setup-java@v4
#        with:
#          java-version: '21'
#          distribution: 'temurin'
#      - name: Publish to GitHub Packages
#        run: mvn --batch-mode deploy
